const allRepos = [
  "chiraag-kakar/createnshare",
  "niloysikdar/Get-Set-Go",
  "niloysikdar/Kahani",
  "niloysikdar/CFI-JGEC",
  "maityamit/Tracky-Track-your-goals-or-targets",
  //   "Kajal13081/Musgenix",
  //   "Kajal13081/Gallery-Application",
  //   "harshita2216/hello-jobs",
  //   "Ly0kami/QuotesApp-JWoC",
  //   "theblockchainchief/web3-hub",
  //   "BRAVO68WEB/url-minify",
  //   "HITK-TECH-Community/Community-Website",
  //   "The-Shivam-garg/BigB-E-learn-Websit-e",
  //   "Codehackerone/Medify",
  //   "aman34503/Go-Airbnb",
  //   "SauravMukherjee44/Aec-Library-Website",
  //   "riyajha2305/Instagram-Clone",
  //   "SaraswatGit/PlanZap",
  //   "abhisheks008/ML-Crate",
  //   "opticSquid/hive",
  //   "gdscjgec/Image-Editor",
  //   "prathimacode-hub/Treksy",
  //   "gdscjgec/Pictionary",
  //   "prathimacode-hub/MedFlare",
  //   "ZiaCodes/counter.js",
  //   "ZiaCodes/claim-prize",
  //   "shibam-naskar/wally",
  //   "harshita214/Chrome-Extension",
  //   "imniladri/DevHub",
  //   "skpandey885/HealhUb",
  //   "sahilsaha7773/SpotLight",
  //   "shibam-naskar/IMAGE_COMPRESOR",
  //   "mohit200008/medi-Care",
  //   "HackClubRAIT/HackClubRAIT-Website.github.io",
  //   "Saup21/Code-Sandbox",
  //   "agamjotsingh18/pollitup",
  //   "neelshah2409/Bot-Collection",
  //   "BlueBlaze6335/Illicit-Illustrations",
  //   "codejay411/Fake-News-Detection-App",
  //   "sagnik1511/Tabular-AutoML",
  //   "Tech-N-Science/FunwithScience",
  //   "smaranjitghose/awesome-portfolio-websites",
  //   "IAmTamal/Milan",
  //   "smaranjitghose/indokhaadyam",
  //   "7saikat7/supply_chain",
];

module.exports = { allRepos };
